services:
  oracledb:
    image: gvenzl/oracle-free:23
    environment:
      ORACLE_PASSWORD: test
      APP_USER: test
      APP_USER_PASSWORD: test
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  oracle-data:
